### ISSUE TITLE
Publish 3.0.1 and 3.1.0

### ISSUE THREAD

**Issue by martinheidegger** [kid-icarus/webshopper-adventure-storage#14]
👋 Hello @workshopper/deploy, @kid-icarus 

@ccarruitero  and me just updated the `workshopper-adventure-storage` module to have new dependencies in [`v3.0.1`](https://github.com/workshopper/workshopper-adventure-storage/releases/tag/v3.0.1) and add promises support in [`v3.1.0`](https://github.com/workshopper/workshopper-adventure-storage/releases/tag/v3.1.0).  As we do not have publish rights on workshopper-adventure-storage, can I ask you to publish both versions? (`3.0.1` to be automatically installed with as a dependency for packages with patch-semver)

**Comment by martinheidegger** [comment]
_Note:_ Travis failed because of a caching issue (fixed now)

**Comment by kid-icarus** [comment]
Done, apologies for the delay.
