### ISSUE TITLE
Travis tests: Down to Node 0.10

### ISSUE THREAD

**Issue by martinheidegger** [kid-icarus/webshopper-adventure-storage#2]
Workshopper is supposed to be running on Node 0.10 (not sure that is still needed). It would be good to run tests in [travis](https://travis-ci.org/) with compatibility down to 0.10.

**Comment by kid-icarus** [comment]
Ah, I didn't know 0.10 support was needed. I'll refactor accordingly, thanks for the feedback :)

**Comment by kid-icarus** [comment]
Done and done :)

https://travis-ci.org/kid-icarus/workshopper-adventure-storage
