### ISSUE TITLE
Standard Formatting

### ISSUE THREAD

**Issue by martinheidegger** [kid-icarus/webshopper-adventure-storage#3]
I am planning to have all workshoppers move to [standard](github.com/feross/standard) standard formatting. It would be cool if this project could follow it too ^_^

**Comment by kid-icarus** [comment]
I also use standard!

I'll set up travis to lint and then close this out.

**Comment by kid-icarus** [comment]
Automated standard linting is in, I prefer using eslint with the standard plugin. Zero linting errors, tested with all versions of node down to 0.10.x:

https://travis-ci.org/kid-icarus/workshopper-adventure-storage

**Comment by martinheidegger** [comment]
I am confused as to why not regular standard but else: 👍
