### ISSUE TITLE
More references

### ISSUE THREAD

**Issue by martinheidegger** [kid-icarus/webshopper-adventure-storage#4]
The storage function was mostly written by me but based on the work of substack and rvagg

**Comment by kid-icarus** [comment]
https://github.com/kid-icarus/workshopper-adventure-storage/commit/6a76aefc6e0837f3464c271228a939ef5ed73ff0 I think this should take care of it, let me know if there's anything else you'd like to see there.

**Comment by martinheidegger** [comment]
LGTM 👍
